/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1s12015_201123065;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author marcosmayen
 */
public class tst extends javax.swing.JFrame {

    /**
     * Creates new form tst
     */
    
    public tst() {
        initComponents();
        matriz(5,5);
    }

    public void matriz(int x,int y)
    {
        int i,j=0;
        JLabel[][] matlbl= new JLabel[x][y];
        for(i=0;i<x;i++)
        {
            for(j=0;j<y;j++)
            {
                matlbl[i][j]= new JLabel(i+","+j);
                matlbl[i][j].setBounds(i*50+70, j*50+50, 50, 50);
                matlbl[i][j].setEnabled(false);
                add(matlbl[i][j]);
                
            }
        }
        paneles(i,j);
    }
    public void fondo(int x, int y)
    {
        ImageIcon icono = new ImageIcon("imagenes/bg.jpg");
        JLabel fondo = new JLabel();
        fondo.setIcon(icono);
        fondo.setBounds(10, 10, 10, 10);
        add(fondo);
        
        
    }
    
    public void paneles(int i, int j)
    {
       
        JPanel PanelP = new JPanel();
        PanelP.setBounds(5, 50, 55, j*50);
        PanelP.setBackground(Color.green);
        add(PanelP);
        
        JPanel PanelZ = new JPanel();
        PanelZ.setBounds(i*50+85, 50, 55, j*50);
        PanelZ.setBackground(Color.BLACK);
        add(PanelZ); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
