
package practica1s12015_201123065;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author marcosmayen
 */
public class VerCatalogo extends javax.swing.JFrame {

    
    
    
    public VerCatalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    ListaEnlazada Persona = new ListaEnlazada();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Imagen");

        jLabel2.setText("Nombre");

        jLabel3.setText("Puntos");

        jLabel4.setText("Ataque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addGap(98, 98, 98)
                .addComponent(jLabel3)
                .addGap(133, 133, 133)
                .addComponent(jLabel4)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void setTipo(ListaEnlazada Lista)
    {
        Persona=Lista;
    }
    
    
    
    
     public void Llenar( ListaEnlazada Lista)
    {
        
        int i;
        JLabel[] imagen = new JLabel[Lista.size()];
        JLabel[] Nombre = new JLabel[Lista.size()];
        JLabel[] Puntos = new JLabel[Lista.size()];
        JLabel[] Ataque = new JLabel[Lista.size()];
        for(i=0;i<Lista.size();i++)
        {
            imagen[i]= new JLabel();
            imagen[i].setBounds(10, 10+100*i, 100, 100);
            ObJugado aux2 =(ObJugado)Lista.obtener(i);
            String file = aux2.getImagen();
            System.out.println(file);
            ImageIcon icon = new ImageIcon(file);
            Image img = icon.getImage();
            
            Image nuevaImg = img.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(nuevaImg);
            imagen[i].setIcon(newicon);
            imagen[i].setSize(150, 175);
            add(imagen[i]);
            
            
            Nombre[i]= new JLabel(aux2.getNombre());
            Nombre[i].setBounds(190, 10+100*i, 200, 100);
            add(Nombre[i]);
            
            String punto = Integer.toString(aux2.getPuntos());
            Puntos[i]= new JLabel(punto);
            Puntos[i].setBounds(350, 10+100*i, 200, 100);
            add(Puntos[i]);
            
            Ataque[i]= new JLabel(aux2.getTipo());
            Ataque[i].setBounds(510, 10+100*i, 200, 100);
            add(Ataque[i]);
            
            /*
            
           
            lblimagenes.setIcon(newicon);
            lblimagenes.setSize(155, 175);
            lblruta.setText(file);
        }
            
            
            
           imagen[i].setIcon(new ImageIcon(file));
            
            ImageIcon icon = new ImageIcon(file);
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(155, 175, java.awt.Image.SCALE_SMOOTH);
            ImageIcon newicon = new ImageIcon(newimg);
            imagen[i].setIcon(newicon);
            imagen[i].setSize(150, 170);*/
            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
